version: '3.1'

services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass myUniquePassword --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis

volumes:
  redis_data:
    driver: local