const HELLO = "HELLO";
const PING = "PING";
const PONG = "PONG";

const WS_UPDATE_USER = "WS_UPDATE_USER";

const WS_REQUEST_FRIEND = "WS_REQUEST_FRIEND";
const WS_ACCEPT_FRIEND_REQUEST = "WS_ACCEPT_FRIEND_REQUEST";
const WS_REJECT_FRIEND_REQUEST = "WS_REJECT_FRIEND_REQUEST";
const WS_BLOCK_USER = "WS_BLOCK_USER";
const WS_UNBLOCK_USER = "WS_UNBLOCK_USER";
const WS_DELETE_FRIEND = "WS_DELETE_FRIEND";

const WS_ADD_CHANNEL = "WS_ADD_CHANNEL";

const WS_JOIN_CHANNEL = "WS_JOIN_CHANNEL";
const WS_LEAVE_CHANNEL = "WS_LEAVE_CHANNEL";

const WS_UPDATE_CHANNEL = "WS_UPDATE_CHANNEL";
const WS_DELETE_CHANNEL = "WS_DELETE_CHANNEL";

const WS_ADD_MEMBER = "WS_ADD_MEMBER";
const WS_DELETE_MEMBER = "WS_DELETE_MEMBER";
const WS_ADMIN_MEMBER = "WS_ADMIN_MEMBER";
const WS_UNADMIN_MEMBER = "WS_UNADMIN_MEMBER";
const WS_BAN_MEMBER = "WS_BAN_MEMBER";
const WS_UNBAN_MEMBER = "WS_UNBAN_MEMBER";

const WS_ADD_MESSAGE = "WS_ADD_MESSAGE";
const WS_DELETE_MESSAGE = "WS_DELETE_MESSAGE";
const WS_ADD_SEEN_MESSAGE = "WS_ADD_SEEN_MESSAGE";

const WS_ADD_POST = "WS_ADD_POST";
const WS_DELETE_POST = "WS_DELETE_POST";
const WS_ADD_POST_LIKE = "WS_ADD_POST_LIKE";
const WS_ADD_POST_COMMENT = "WS_ADD_POST_COMMENT";

const WS_ADD_WATCHER = "WS_ADD_WATCHER";
const WS_DELETE_WATCHER = "WS_DELETE_WATCHER";

const WS_ADD_VIDEO = "WS_ADD_VIDEO";
const WS_DELETE_VIDEO = "WS_DELETE_VIDEO";

const WS_REQUEST_CHANNEL_FOLLOW = "WS_REQUEST_CHANNEL_FOLLOW";
const WS_ACCEPT_CHANNEL_FOLLOW_REQUEST = "WS_ACCEPT_CHANNEL_FOLLOW_REQUEST";
const WS_REJECT_CHANNEL_FOLLOW_REQUEST = "WS_REJECT_CHANNEL_FOLLOW_REQUEST";

const WS_ADD_NOTIFICATION = "WS_ADD_NOTIFICATION";
const WS_DELETE_NOTIFICATION = "WS_DELETE_NOTIFICATION";

const userEvents = [
  WS_REQUEST_FRIEND,
  WS_ACCEPT_FRIEND_REQUEST,
  WS_REJECT_FRIEND_REQUEST,
  WS_BLOCK_USER,
  WS_UNBLOCK_USER,
  WS_DELETE_FRIEND,
  WS_ADD_CHANNEL,
  WS_JOIN_CHANNEL,
  WS_LEAVE_CHANNEL
];

const channelEvents = [
  WS_UPDATE_CHANNEL,
  WS_DELETE_CHANNEL,
  WS_ADD_MEMBER,
  WS_DELETE_MEMBER,
  WS_ADMIN_MEMBER,
  WS_UNADMIN_MEMBER,
  WS_BAN_MEMBER,
  WS_UNBAN_MEMBER,
  WS_ADD_MESSAGE,
  WS_DELETE_MESSAGE,
  WS_ADD_SEEN_MESSAGE,
  WS_ADD_POST,
  WS_DELETE_POST,
  WS_ADD_POST_LIKE,
  WS_ADD_POST_COMMENT,
  WS_ADD_WATCHER,
  WS_DELETE_WATCHER,
  WS_ADD_VIDEO,
  WS_DELETE_VIDEO,
  WS_REQUEST_CHANNEL_FOLLOW,
  WS_ACCEPT_CHANNEL_FOLLOW_REQUEST,
  WS_REJECT_CHANNEL_FOLLOW_REQUEST
];

const channelsEvents = [WS_UPDATE_USER];

module.exports = {
  HELLO,
  PING,
  PONG,
  WS_UPDATE_USER,
  WS_REQUEST_FRIEND,
  WS_ACCEPT_FRIEND_REQUEST,
  WS_REJECT_FRIEND_REQUEST,
  WS_BLOCK_USER,
  WS_UNBLOCK_USER,
  WS_DELETE_FRIEND,
  WS_ADD_CHANNEL,
  WS_JOIN_CHANNEL,
  WS_LEAVE_CHANNEL,
  WS_UPDATE_CHANNEL,
  WS_DELETE_CHANNEL,
  WS_ADD_MEMBER,
  WS_DELETE_MEMBER,
  WS_ADMIN_MEMBER,
  WS_UNADMIN_MEMBER,
  WS_BAN_MEMBER,
  WS_UNBAN_MEMBER,
  WS_ADD_MESSAGE,
  WS_DELETE_MESSAGE,
  WS_ADD_SEEN_MESSAGE,
  WS_ADD_POST,
  WS_DELETE_POST,
  WS_ADD_POST_LIKE,
  WS_ADD_POST_COMMENT,
  WS_ADD_WATCHER,
  WS_DELETE_WATCHER,
  WS_ADD_VIDEO,
  WS_DELETE_VIDEO,
  WS_REQUEST_CHANNEL_FOLLOW,
  WS_ACCEPT_CHANNEL_FOLLOW_REQUEST,
  WS_REJECT_CHANNEL_FOLLOW_REQUEST,
  WS_ADD_NOTIFICATION,
  WS_DELETE_NOTIFICATION,
  userEvents,
  channelEvents,
  channelsEvents
};
