const HELLO = "WS_HELLO";
const PING = "WS_PING";
const PONG = "WS_PONG";

const WS_UPDATE_USER = "WS_UPDATE_USER";

const WS_DELETE_SENT_FRIEND_REQUEST = "WS_DELETE_SENT_FRIEND_REQUEST";
const WS_ADD_RECEIVED_FRIEND_REQUEST = "WS_ADD_RECEIVED_FRIEND_REQUEST";
const WS_DELETE_RECEIVED_FRIEND_REQUEST = "WS_DELETE_RECEIVED_FRIEND_REQUEST";
const WS_ADD_FRIEND = "WS_ADD_FRIEND";
const WS_ADD_BLOCKER = "WS_ADD_BLOCKER";
const WS_DELETE_BLOCKER = "WS_DELETE_BLOCKER";

const WS_UNFRIEND = "WS_UNFRIEND";
const WS_BLOCK_FRIEND = "WS_BLOCK_FRIEND";
const WS_DELETE_FRIEND = "WS_DELETE_FRIEND";
const WS_DELETE_FRIEND_ROOM = "WS_DELETE_FRIEND_ROOM";

const WS_ADD_CHANNEL = "WS_ADD_CHANNEL";

const WS_SUBSCRIBE_CHANNEL = "WS_SUBSCRIBE_CHANNEL";
const WS_UNSUBSCRIBE_CHANNEL = "WS_SUBSCRIBE_CHANNEL";

const WS_JOIN_CHANNEL = "WS_JOIN_CHANNEL";
const WS_LEAVE_CHANNEL = "WS_LEAVE_CHANNEL";

const WS_UPDATE_CHANNEL = "WS_UPDATE_CHANNEL";
const WS_DELETE_CHANNEL = "WS_DELETE_CHANNEL";

const WS_ADD_MEMBER = "WS_ADD_MEMBER";
const WS_ADD_MEMBERS = "WS_ADD_MEMBERS";
const WS_DELETE_MEMBER = "WS_DELETE_MEMBER";
const WS_ADD_ADMIN = "WS_ADD_ADMIN";
const WS_DELETE_ADMIN = "WS_DELETE_ADMIN";
const WS_ADD_BAN = "WS_ADD_BAN";
const WS_DELETE_BAN = "WS_DELETE_BAN";

const WS_ADD_MESSAGE = "WS_ADD_MESSAGE";
const WS_DELETE_MESSAGE = "WS_DELETE_MESSAGE";
const WS_ADD_SEEN_MESSAGE = "WS_ADD_SEEN_MESSAGE";

const WS_ADD_POST = "WS_ADD_POST";
const WS_DELETE_POST = "WS_DELETE_POST";
const WS_ADD_POST_LIKE = "WS_ADD_POST_LIKE";
const WS_DELETE_POST_LIKE = "WS_DELETE_POST_LIKE";

const WS_ADD_COMMENT = "WS_ADD_COMMENT";
const WS_DELETE_COMMENT = "WS_DELETE_COMMENT";

const WS_ADD_WATCHER = "WS_ADD_WATCHER";
const WS_DELETE_WATCHER = "WS_DELETE_WATCHER";

const WS_ADD_VIDEO = "WS_ADD_VIDEO";
const WS_DELETE_VIDEO = "WS_DELETE_VIDEO";

const WS_REQUEST_CHANNEL_FOLLOW = "WS_REQUEST_CHANNEL_FOLLOW";
const WS_ACCEPT_CHANNEL_FOLLOW_REQUEST = "WS_ACCEPT_CHANNEL_FOLLOW_REQUEST";
const WS_REJECT_CHANNEL_FOLLOW_REQUEST = "WS_REJECT_CHANNEL_FOLLOW_REQUEST";

const WS_ADD_NOTIFICATION = "WS_ADD_NOTIFICATION";
const WS_DELETE_NOTIFICATION = "WS_DELETE_NOTIFICATION";

const userEvents = [
  WS_DELETE_SENT_FRIEND_REQUEST,
  WS_ADD_RECEIVED_FRIEND_REQUEST,
  WS_DELETE_RECEIVED_FRIEND_REQUEST,
  WS_ADD_FRIEND,
  WS_DELETE_FRIEND,
  WS_ADD_BLOCKER,
  WS_DELETE_BLOCKER,
  WS_ADD_CHANNEL,
  WS_SUBSCRIBE_CHANNEL,
  WS_UNSUBSCRIBE_CHANNEL
];

const userChannelEvents = [
  WS_JOIN_CHANNEL,
  WS_LEAVE_CHANNEL,
  WS_UNFRIEND,
  WS_BLOCK_FRIEND
];

const channelEvents = [
  WS_UPDATE_CHANNEL,
  WS_DELETE_CHANNEL,
  WS_DELETE_FRIEND_ROOM,
  WS_ADD_MEMBER,
  WS_ADD_MEMBERS,
  WS_DELETE_MEMBER,
  WS_ADD_ADMIN,
  WS_DELETE_ADMIN,
  WS_ADD_BAN,
  WS_DELETE_BAN,
  WS_ADD_MESSAGE,
  WS_DELETE_MESSAGE,
  WS_ADD_SEEN_MESSAGE,
  WS_ADD_POST,
  WS_DELETE_POST,
  WS_ADD_POST_LIKE,
  WS_DELETE_POST_LIKE,
  WS_ADD_COMMENT,
  WS_DELETE_COMMENT,
  WS_ADD_WATCHER,
  WS_DELETE_WATCHER,
  WS_ADD_VIDEO,
  WS_DELETE_VIDEO,
  WS_REQUEST_CHANNEL_FOLLOW,
  WS_ACCEPT_CHANNEL_FOLLOW_REQUEST,
  WS_REJECT_CHANNEL_FOLLOW_REQUEST
];

const channelsEvents = [WS_UPDATE_USER];

module.exports = {
  HELLO,
  PING,
  PONG,
  WS_UPDATE_USER,
  WS_DELETE_SENT_FRIEND_REQUEST,
  WS_ADD_RECEIVED_FRIEND_REQUEST,
  WS_DELETE_RECEIVED_FRIEND_REQUEST,
  WS_ADD_FRIEND,
  WS_DELETE_FRIEND,
  WS_ADD_BLOCKER,
  WS_DELETE_BLOCKER,
  WS_UNFRIEND,
  WS_BLOCK_FRIEND,
  WS_ADD_CHANNEL,
  WS_JOIN_CHANNEL,
  WS_LEAVE_CHANNEL,
  WS_UPDATE_CHANNEL,
  WS_DELETE_CHANNEL,
  WS_DELETE_FRIEND_ROOM,
  WS_ADD_MEMBER,
  WS_ADD_MEMBERS,
  WS_DELETE_MEMBER,
  WS_ADD_ADMIN,
  WS_DELETE_ADMIN,
  WS_ADD_BAN,
  WS_DELETE_BAN,
  WS_ADD_MESSAGE,
  WS_DELETE_MESSAGE,
  WS_ADD_SEEN_MESSAGE,
  WS_ADD_POST,
  WS_DELETE_POST,
  WS_ADD_COMMENT,
  WS_DELETE_COMMENT,
  WS_ADD_POST_LIKE,
  WS_DELETE_POST_LIKE,
  WS_ADD_WATCHER,
  WS_DELETE_WATCHER,
  WS_ADD_VIDEO,
  WS_DELETE_VIDEO,
  WS_REQUEST_CHANNEL_FOLLOW,
  WS_ACCEPT_CHANNEL_FOLLOW_REQUEST,
  WS_REJECT_CHANNEL_FOLLOW_REQUEST,
  WS_ADD_NOTIFICATION,
  WS_DELETE_NOTIFICATION,
  WS_SUBSCRIBE_CHANNEL,
  WS_UNSUBSCRIBE_CHANNEL,
  userEvents,
  userChannelEvents,
  channelEvents,
  channelsEvents
};
