DROP SCHEMA IF EXISTS public CASCADE;
DROP EXTENSION IF EXISTS btree_gist;
DROP EXTENSION IF EXISTS citext;
DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS pg_hashids;
